version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "kube-linter"
type = "community"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "php"

[[analyzers]]
name = "swift"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "ansible"